name: ci

on:
    workflow_dispatch:
    push:
        paths-ignore:
            - README.md

permissions:
    packages: write

jobs:
    docker:
        strategy:
            matrix:
                rust_version: ['1.69', '1.70', '1.71', '1.72', '1.73', 'stable']
                include:
                - rust_version: 'stable'
                  docker_tag: 'latest'

        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Login to DockerHub
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Set up Docker buildx
              uses: docker/setup-buildx-action@v2

            - name: Build and push
              uses: docker/build-push-action@v4
              with:
                  build-args: |
                    RUST_VERSION=${{matrix.rust_version}}
                  file: ./Dockerfile
                  push: ${{github.ref == 'refs/heads/main'}}
                  tags: ghcr.io/kws-electronic/aarch64-openssl-rs:${{matrix.docker_tag || matrix.rust_version}}
